# site settings
title: Aakash Prasad
subtitle: Cybersecurity
email: prasad.aakash@gmail.com
description: Hello my name is Aakash Prasad<br /> and this is my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 360 Huntington Ave
city: Boston
state: MA
zip_code: 02115
country: United States of America
phone: Please refer resume

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/SkySecCoder
gitlab_url:  
googleplus_url: 
instagram_url: https://www.instagram.com/aakash_bazinga/
linkedin_url: https://www.linkedin.com/in/aakash-prasad-590761a4/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
